version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esales
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    image: wodby/drupal-php:7.1-3.0.0
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: esales
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
    volumes:
      - ./:/var/www/html

  apache:
    image: wodby/php-apache:2.4-2.0.0
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    labels:
      traefik.backend: 'apache'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:esales.localhost'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      traefik.backend: 'pma'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:pma.esales.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.backend: 'portainer'
      traefik.port: '9000'
      traefik.frontend.rule: 'Host:portainer.mini-framework.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
